<a href="https://colab.research.google.com/github/TimkaThymineTimiryazevskaya/sf_data_science/blob/main/MATHML_Module_1_Matrix_Base_screencast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# как создать матрицу?

In [2]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [3]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# размер матрицы
np.shape(A)

(4, 3)

In [5]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [6]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [7]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [8]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [9]:
# создание специальных матриц

In [10]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [15]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [16]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [17]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [18]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [ ]:
B+A

In [ ]:
A-B

In [ ]:
2*A

In [19]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [20]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [21]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [22]:
x_col.T

array([[1, 2, 3]])

In [23]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [24]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [25]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
print(Inc.T)

[[100 150  90]
 [220 200  80]
 [140 130 100]]


In [26]:
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
print(Cons.T)

[[ 50 100 100]
 [ 50  80  20]
 [ 60 140 140]]


In [28]:
a = Inc.T
print(a*0.87)

[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]


In [31]:
print(a*0.87-Cons.T)

[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


In [32]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [33]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [34]:
A = np.matrix("1,2,1;1,-1,2")
A

matrix([[ 1,  2,  1],
        [ 1, -1,  2]])

In [35]:
G = A.T*A
G

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [41]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [43]:
print(A@x)

[26 30]


In [44]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [47]:
print(B@A)

[[  2   9  11  14]
 [  8 -10 -14 -11]]


In [48]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [51]:
A = np.array([x,y,z])
G = (A.T@A)
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [52]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [53]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [56]:
A = np.array(Count_DF.values)
B = np.array(Price_DF.values)

In [59]:
C = A.T@B
C

array([[175.5, 169.8, 115.7,  63.2, 129.4],
       [164.8, 197.1, 108.9,  68.9, 112.7],
       [283.2, 279.6, 208.9,  91. , 165.3],
       [474.7, 483.3, 295.2, 165.7, 312.5],
       [300.8, 299. , 202. , 100. , 181. ]])

In [61]:
com1 = np.ones(1)-com

In [64]:
print(com@C)

[230.57 235.49 157.31  80.29 147.36]


In [66]:
salon_inc = (A*B)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [69]:
print((A*B)@(com1))

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [2]:
A = np.matrix("1,2;2,5")
print(np.linalg.inv(A))

[[ 5. -2.]
 [-2.  1.]]


In [4]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))


2


In [5]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
print(np.linalg.inv(A))

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


In [6]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [7]:
A= np.array([v1,v2,v3,v4]).T
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [8]:
print(np.linalg.matrix_rank(A))

4


In [9]:
print(A.T@A)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [10]:
print(np.linalg.det(A.T@A))

3716647.9999999995


In [11]:
print(np.linalg.inv(A.T@A))

[[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
