<a href="https://colab.research.google.com/github/TimkaThymineTimiryazevskaya/sf_data_science/blob/main/%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,3,5])
v2 = np.array([4,-4,9])
v3 = np.array([13,7,12])
A = np.array([v1,v2,v3])

eig_values, eig_vectors = np.linalg.eig(A)

print(eig_values)

[19.52189628 -3.75422737 -6.76766891]


In [4]:
v1 = np.array([1,9,4])
v2 = np.array([9,4,7])
v3 = np.array([4,7,12])
A = np.array([v1,v2,v3])

eig_values, eig_vectors = np.linalg.eig(A.T@A)

print(eig_values)
print(eig_vectors)

[391.37004987  45.77088847  15.85906166]
[[-0.41955589 -0.7323045  -0.5363795 ]
 [-0.55709648  0.67425896 -0.48478693]
 [-0.71667034 -0.09541992  0.69085358]]


In [6]:
import numpy as np
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([
[1, 0.9922],
[0.9922, 1],
])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

## [-0.24  0.86 -0.29 -0.33]

[-0.24  0.86 -0.29 -0.33]
